#include "Tester.hpp"
#include "SinglyLinkedList.hpp"
#include "DoublyLinkedList.hpp"
#include "DynamicArray.hpp"
#include <iostream>
#include <vector>
#include <chrono>
#include <random>
#include <fstream>
